import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { RouteLoader } from '@/components/RouteLoader'
import { ThemeProviderClient } from '@/components/ThemeProviderClient'
import { MoodManager } from '@/components/MoodManager'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviderClient>
          <RouteLoader />
          <MoodManager />
          {children}
        </ThemeProviderClient>
      </body>
    </html>
  );
}
